name: 'NPM Actions'
description: 'NPM Actions install, publish, tag'
inputs:
  context:
    description: 'Git Context'
    default: ${{ toJson(github) }}
  working-directory:
    description: 'Process directory'
  token:
    description: 'NPM Token'
  command:
    description: 'Allowed values: install, publish, version.'
outputs:
  result: 
    description: ''
runs:
  using: 'node20'
  main: 'index.js'