name: Action Build
on:
  push:
    branches:    
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      - 
        name: Setup Node
        run: npm i
      - 
        name: Build
        run: npm run build
      - 
        name: Cleanup
        run: rm -rf src/* package-lock.json
      -
        name: Tag
        run: |
          VERSION=$(node -p "require('./package.json').version.split('.')[0]")
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag v$VERSION already exists. Deleting it."
            git tag -d "v$VERSION"
            git push --delete origin "v$VERSION"
          fi
          git config user.email "devops@vistta.org"
          git config user.name "devops"
          git commit -m "v$VERSION" -a
          git tag "v$VERSION"
          git push origin "v$VERSION"
          echo "Tagged v$VERSION"
