name: Action Build
on:
  push:
    branches:    
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      - 
        name: Setup Node
        run: npm i
      - 
        name: Build
        run: npm run build
      -
        name: Tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag v$VERSION already exists. Deleting it."
            git tag -d "v$VERSION"
            git push --delete origin "v$VERSION"
          fi
          git tag "v$VERSION"
          git push origin "v$VERSION"
          echo "Tagged v$VERSION"
