name: Action Build
on:
  push:
    branches:    
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      - 
        name: Setup Node
        run: npm i
      - 
        name: Build
        run: npm run build
